"use strict";
// lang-pt.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_EN_NAME = 'en';
exports.LANG_EN_TRANS = {
    'hello world': 'Ola mundo',
    'hello greet': 'Ola, %0 %1!',
    'well done': '%0 Bem Vindo',
    'common-msg-success-header': 'Sucesso',
    'common-msg-info-header': 'Informação',
    'common-msg-warn-header': 'Aviso',
    'common-msg-error-header': 'Erro',
    'common-msg-success': 'Execução Ok',
    'common-msg-info': 'Acesso negado',
    'common-msg-warn': 'Erro negocial',
    'common-msg-error': 'Erro interno',
    'common-msg-403': 'Acesso negado',
    'login_lb_title': 'título Login',
    'login-lb-user': 'Usuário',
    'login-lb-password': 'Senha',
    'btn-new-simulation': 'New Simulation',
    'btn-my-proposals': 'My proposal',
    'btn-login': 'Login',
    'btn-my-profile': 'Perfil',
    'btn-administration': 'Administração',
    'btn-insurance': 'Seguros',
    'lb-change-password': 'Alteração de senha',
    'lb-change-password-field-required': 'Campo Obrigatório! (mínimo 6 caracteres)',
    'lb-current-password': 'Senha Atual',
    'lb-new-password': 'Nova Senha',
    'lb-confirm-password': 'Confirmação de Senha',
    'btn-notifications': 'Notificações',
    'btn-change-brand': 'Trocar Marca',
    //Todos
    'btn-edit': 'Editar',
    'btn-save': 'Salvar',
    'btn-clear': 'Limpar',
    'btn-delete': 'Excluir',
    'lk-forgot-password': 'Esqueci minha senha',
    'forgot-password-lb-useremail': 'Usuário/e-mail',
    'forgot-password-msg': 'Informe seu usuário ou endereço de e-mail para estar recebendo um e-mail com o link pra criar a nova senha',
    //Home
    'lb-news': 'Notícias-EN',
    'lb-support': 'Suporte-EN',
    'lb-some-problem-in': 'Algum problema no uso do',
    'check-here-the-most-frequently-asked-questions': 'Consulte aqui as questões mais frequentes',
    //Menu
    'btn-deactivation-of-services': 'Desativação de Serviços',
    'btn-services-configuration': 'Configuração de Serviços',
    'btn-dealer-proposal': 'Propostas com Alteração de Concessionária',
    'btn-required': 'Obrigatório',
    'btn-commission-level': 'Liberação de Retorno',
    'btn-submission-process-configuration': 'Configuração do Processo de Submissão',
    'btn-proposal-update': 'Atualização de Proposta',
    'btn-news-administration': 'Administração de notícias',
    'btn-promotional-images': 'Imagens Promocionais',
    'btn-models': 'Modelos',
    //Modelo
    'lb-brand': 'Marca',
    'btn-choose-file': 'Escolher Arquivo',
    'btn-remove': 'Remover',
    'lb-vehicle-band': 'Marca do Veículo',
    'lb-vehicle-model': 'Modelo do Veículo',
    'lb-version': 'Versão',
    'msg-image-size': 'A imagem deve possuir as dimensões mínimas de 1024x435 px e tamanho máximo de 8MB.',
    //Login
    'lb-welcome': 'Bem-vindo',
    //Nova Inserção
    'btn-search': 'Procurar',
    'btn-reset': 'Redefinir',
    'btn-enter': 'Entrar',
    'lb-proposal-number': 'Número da Proposta',
    'lb-customer-type': 'Tipo Cliente',
    'btn-logout': 'Sair',
    'btn-send': 'Enviar',
    //Minhas Propostas
    'lb-my-agreements': 'Minhas Propostas',
    'lb-status-proposal': 'Status da Proposta',
    'lb-date-initial-creation': 'Date de Criação Inicial',
    'lb-date-final-creation': 'Data Criação Final',
    'lb-date-initial-validate': 'Data Validade Inicial',
    'lb-date-final-validate': 'Data Validade Final',
    'lb-concessionaire': 'Concessionária',
    'lb-exemption': 'Isenção',
    //Formulário Cliente
    'lb-custumer-personal-data': 'DADOS PESSOAIS DO CLIENTE',
    'lb-cpf-cnpj': 'CPF ou CNPJ',
    'lb-client-name': 'Nome do Cliente',
    'lb-contact-information': 'Dados de Contato',
    'lb-phone-number': 'Telefone do Cliente',
    'lb-localization': 'Localização',
    'lb-state': 'Estado',
    'lb-select-state': 'Selecione um Estado',
    'lb-simulation-information': 'Informações de Simulação',
    'lb-direct-sale': 'Venda Direta',
    'lb-new-ones': 'Seminovos',
    'lb-sale-type': 'Tipo de Venda',
    'btn-choose-vehicle': 'Escolher Veículo',
    'lb-brands': 'Marcas',
    'lb-simulate': 'Simular',
    'lb-model': 'Modelo',
    //Noticias Administrativas
    'lb-create-by': 'Criado por',
    'lb-creation-date': 'Data de Criação',
    'lb-financial-brands': 'Marcas financeiras',
    'lb-publish': 'Publicar',
    'btn-save-news': 'Salvar Notícia',
    'lb-list-of-registered-news': 'Lista de notícias cadastradas',
    'lb-new-title': 'Título da Notícia',
    'lb-actions': 'Ações',
    //Liberação de Retorno
    'lb-commission-level': 'Liberação de Retorno',
    'lb-vendor-manager': 'Vendedor / Gerente',
    'lb-select-a': 'Selecione um',
    'lb-product': 'Produto',
    'lb-select-return': 'Selecione retorno',
    'lb-release': 'Liberar',
    'btn-release': 'Liberar',
    'lb-release-date': 'Data de liberação',
    'lb-fleet-code': 'Código Frota',
    'lb-commission-level-date': 'Data de Liberação',
    'lb-release-by': 'Liberador Por',
    'lb-released-level': 'Retorno Liberado',
    'lb-validate': 'Validade',
    'lb-proposal': 'Proposta',
    'lb-salesman': 'Vendedor',
    //Proposta com alteração de Concessionaria (dealer_proposal)
    'lb-dealer-proposal': 'Propostas com Alteração de Concessionária',
    'lb-client': 'Cliente',
    'lb-status': ' Status',
    'lb-financed': 'Financiado',
    'lb-table': 'Tabela',
    'lk-reassign': 'Reatribuir',
    'lb-detailing': 'Detalhamento',
    'lb-reassign': 'Reatribuir',
    'lb-amount-financed': 'Montante Financiado',
    'lb-validate-date': 'Data Validade',
    'lb-previous-concessionaire': 'Concessionária Anterior',
    'lb-new-concessionaire': 'Nova Concessionária',
    // 'btn-new-simulation':'New Simulation',
    // 'btn-my-proposals':'My Proposals',
    // 'btn-login':'Login',
    // 'btn-my-profile':'Perfil',
    // 'btn-administration': 'Administração',
    // 'btn-insurance': 'Seguros',
    //Documentos
    'lb-the-proposal-number': 'A PROPOSTA NÚMERO',
    'lb-name': 'Nome',
    //Simulacao
    'lb-simulation-print': 'Imprimir',
    'lb-required-field': 'campo obrigatório',
    //Perfil
    'simulation-windows': 'JANELAS DE SIMULAÇÃO',
    'windows': 'Janelas',
    'language': 'IDIOMA',
    'change-password2': 'TROCAR SENHA',
    'logout2': 'SAIR'
};
//# sourceMappingURL=lang-en.js.map